name: Cloudy
version: 'v1.1.2'
main: me.kaketuz.cloudy.Cloudy
api-version: '1.20'
authors: [ Lord_Cacetus_ ]
description: This pack will adds a lot of interesting abilities and a new SubElement - Steam!
commands:
  cloudy:
    description: reload command
    usage: /cloudy|cl|cldy reload
    aliases:
      - cl
      - cldy